name: 'Continuous Integration'
on:
  pull_request:
    branches:
      - master
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Run unit tests
        run: npm run test
